version: '3.8'
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: springrestdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: 5978450740
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: '2g'
        reservations:
          cpus: '1'
          memory: '1g'

  app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - .:/app
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springrestdb
      SPRING_DATASOURCE_USERNAME: testuser
      SPRING_DATASOURCE_PASSWORD: 5978450740
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    deploy:
      resources:
        limits:
          cpus: '3'
          memory: '4g'
        reservations:
          cpus: '2'
          memory: '3g'

volumes:
  mysql_data:
    driver: local
